version: "3.7"

networks:
  backend:

services:

  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://stainless:abc123@db/stainless
    volumes:
      - .:/app

# TODO wait for DB container before starting Flask

  db:
    image: postgres:12.2-alpine
    hostname: postgres
    depends_on:
      - adminer
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data:cached
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      POSTGRES_USER: stainless
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: stainless
    tty: true
    stdin_open: false

  adminer:
    image: adminer
    hostname: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      ADMINER_DESIGN: 'galkaev'